if(($#!=1)); then
    echo "Usage: $0 <MESHFACTOR (positive integer >1)>"
    echo "This shell creates a symbolic link to a folder QVECTORSXXX."
    echo "Such folder contains wavenumber files named qvector.xxx, generated by grouping the files QVECTORS/qvector.yyy with a mesh factor MESHFACT."
    exit 1
fi
if(($1<=1)); then
    echo "MESHFACTOR must be a positive integer >1"
    exit 1
fi
echo $#
M=$1 #meshfactor
nmax=300

dest1="/media/flavio/Seagate Basic/TESI/GROMACS-OTP/QVECTORS/"
printf -v dest "/media/flavio/Seagate Basic/TESI/GROMACS-OTP/QVECTORS%03d/" $M
ls "$dest" 2> /dev/null
result=$? #does folder exist?
nfiles=$(ls "$dest" 2> /dev/null | wc -l) #how many files does it contain?
if(($result==0)); then
    echo "Already created: "$dest
else #create the folder and the link to it
    printf -v linkname "QVECTORS%03d" $M
    mkdir "$dest"
    ln -s "$dest" $link
    echo "Link created: "$linkname
fi

if((nfiles>0)); then
    echo "... and already filled with qvector.xxx files"
    exit 1
fi

# else create the files, collecting the ones in QVECTORS
echo "Creating ${linkname}/qvector.n from QVECTORS/qvector.k (concatenate k's, shuffle and selected at most $nmax lines) ..."

for((n=1;n<=$nmax;n++)); do
    echo "n="$n
    rm tmp 2> /dev/null #empty the tmp file
    k1=$( echo "($n-1)*($M)*2 + 1" | bc -l )
    k2=$( echo "($n)*($M)*2" | bc -l )
    
    for((k=$k1;k<=$k2 && k<=$nmax;k++)); do
	if(($k==1)); then continue; fi #there's no file QVECTORS/qvector.001
	echo "* k="$k
	printf -v source "${dest1}""qvector.%03d" $k
	#echo "source="$source
	cat "$source" >> tmp #append qvectors to tmp file
	if(($?!=0)); then break; fi
    done
    
    nlines=$(cat tmp 2> /dev/null | wc -l)
    if((nlines==0)); then break; fi #maximum wavevector reached
    
    printf -v qvecfile "${dest}""qvector.%03d" $n
    shuf tmp -n $nmax > "$qvecfile"
    echo ""
done
rm tmp
echo "...done"
